#!/usr/bin/env python3

import shapescript, sys

try:
	for item in shapescript.interpret(open(sys.argv[1]).read()):
		print(item, end = '')
except IndexError:
	print('Syntax: %s source-file' % argv[0], file = sys.stderr)
	exit(1)
